import { FormEvent, useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { post, useGame, useRemainingSeconds } from "../game";
import type { GameState, Team } from "../types";

type HostAction = "start" | "finish" | "pause" | "add-time" | "reset" | "approval" | "approve" | "reject" | "remove" | "approve-all";
type Command = (action: HostAction, extra?: object) => void;
const hostTokenKey = "bkb-host-token";
function savedHostToken() { try { return sessionStorage.getItem(hostTokenKey); } catch { return null; } }
function saveHostToken(token: string | null) { try { if (token) sessionStorage.setItem(hostTokenKey, token); else sessionStorage.removeItem(hostTokenKey); } catch { /* storage blocked: the PIN is asked again after a reload */ } }
// Phones can't reach "localhost", so in local dev the QR code asks the dev server for this machine's LAN address.
const isLocalHost = ["localhost", "127.0.0.1"].includes(window.location.hostname);

// Removing a team takes two clicks: the first turns the button into "Emin misiniz?" for a few seconds.
function Scoreboard({ teams, command }: { teams: Team[]; command: Command }) {
  const [confirming, setConfirming] = useState<string | null>(null);
  useEffect(() => { if (!confirming) return; const timer = window.setTimeout(() => setConfirming(null), 4_000); return () => window.clearTimeout(timer); }, [confirming]);
  return <aside className="panel rounded-3xl p-6"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Canlı skor</p><ol className="mt-5 space-y-3">{teams.map((team, index) => <li className="group flex items-center justify-between gap-3 rounded-2xl bg-white/5 px-4 py-3" key={team.id}><span className="min-w-0 flex-1 truncate">{index + 1}. {team.name}</span><button className={`rounded-lg px-2 py-1 text-xs ${confirming === team.id ? "bg-red-500 text-white" : "text-slate-400 opacity-0 hover:text-red-300 focus:opacity-100 group-hover:opacity-100"}`} onClick={() => { if (confirming === team.id) { setConfirming(null); command("remove", { teamId: team.id }); } else setConfirming(team.id); }} type="button">{confirming === team.id ? "Emin misiniz?" : "Çıkar"}</button><strong className="text-2xl text-cyan-300">{team.score}</strong></li>)}</ol></aside>;
}

// The host screen is usually the projector, so names waiting for approval stay hidden until the host chooses to show them.
function Approvals({ state, command, lobby }: { state: GameState; command: Command; lobby: boolean }) {
  const [revealed, setRevealed] = useState(false);
  const pending = state.pendingTeams ?? [];
  if (!lobby && !pending.length) return null;
  return <section className="panel rounded-3xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Katılım onayı</p>{lobby && <button className={`rounded-full px-4 py-1 text-sm font-semibold ${state.approvalRequired ? "bg-cyan-400 text-slate-950" : "border border-white/30 text-slate-300"}`} onClick={() => command("approval", { enabled: !state.approvalRequired })} type="button">Host onayı: {state.approvalRequired ? "Açık" : "Kapalı"}</button>}</div>{pending.length ? <><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span><strong className="text-2xl text-cyan-300">{pending.length}</strong> takım onay bekliyor</span><div className="flex gap-2"><button className="rounded-lg border border-white/30 px-3 py-1 text-sm" onClick={() => setRevealed(!revealed)} type="button">{revealed ? "Gizle" : "Göster"}</button><button className="rounded-lg bg-cyan-400 px-3 py-1 text-sm font-bold text-slate-950" onClick={() => command("approve-all")} type="button">Tümünü onayla</button></div></div>{revealed && <ul className="mt-4 space-y-2">{pending.map((team) => <li className="flex items-center justify-between gap-3 rounded-xl bg-white/5 px-4 py-2" key={team.id}><span className="min-w-0 flex-1 truncate">{team.name}</span><button className="rounded-lg bg-emerald-400 px-3 py-1 text-sm font-bold text-slate-950" onClick={() => command("approve", { teamId: team.id })} type="button">Onayla</button><button className="rounded-lg border border-red-300 px-3 py-1 text-sm text-red-200" onClick={() => command("reject", { teamId: team.id })} type="button">Reddet</button></li>)}</ul>}</> : <p className="mt-4 text-sm text-slate-400">{state.approvalRequired ? "Onay bekleyen takım yok." : "Takımlar onaysız katılıyor."}</p>}</section>;
}

export function HostPage() {
  const [pin, setPin] = useState("");
  const [token, setToken] = useState(savedHostToken);
  const [error, setError] = useState("");
  const { state, serverNow } = useGame({ token, onUnauthorized: () => { saveHostToken(null); setToken(null); setError("Host oturumunun süresi doldu. PIN'i yeniden girin."); } });
  const [joinUrl, setJoinUrl] = useState(`${window.location.origin}/join`);
  const remaining = useRemainingSeconds(state, serverNow);
  useEffect(() => { if (isLocalHost) fetch(`/api/join-url?port=${window.location.port || "80"}`).then((response) => response.json()).then(({ url }) => setJoinUrl(url)).catch(() => undefined); }, []);
  async function authenticate(event: FormEvent) { event.preventDefault(); const result = await post<{ token: string }>("/api/host-login", { pin }); if (result.ok) { saveHostToken(result.token); setToken(result.token); setError(""); } else setError(result.message ?? "PIN doğrulanamadı."); }
  function command(action: HostAction, extra: object = {}) { post("/api/host-command", { action, ...extra }, token).then((result) => { if (result.status === 401) { saveHostToken(null); setToken(null); } setError(result.ok ? "" : result.message ?? "Komut uygulanamadı."); }); }
  const notice = error ? <p className="fixed bottom-6 left-1/2 -translate-x-1/2 rounded-xl bg-red-500/90 px-5 py-3 font-semibold text-white">{error}</p> : null;
  if (!token) return <main className="app-shell flex min-h-screen items-center justify-center p-6"><form className="panel w-full max-w-md rounded-3xl p-10" onSubmit={authenticate}><h1 className="text-4xl font-bold">Bir Kelime Bir İşlem</h1><label className="mt-8 block">Host PIN</label><input autoFocus className="mt-2 w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3" onChange={(event) => setPin(event.target.value)} type="password" value={pin} />{error && <p className="mt-3 text-red-300">{error}</p>}<button className="mt-6 w-full rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Devam et</button></form></main>;
  const isActive = state.phase === "word" || state.phase === "number";
  if (isActive && state.round) return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-8 flex justify-between"><div><p className="text-cyan-300">{state.matchRound}. tur / {state.totalRounds} · {state.round.type === "word" ? "Kelime" : "İşlem"}</p><h1 className="text-4xl font-bold">{state.round.type === "word" ? "Bir Kelime" : "Bir İşlem"}</h1></div><strong className="text-6xl text-cyan-300">{remaining}s</strong></header><div className="h-4 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-cyan-400" style={{ width: `${(remaining / state.round.durationSeconds) * 100}%` }} /></div><div className="mt-8 grid gap-8 xl:grid-cols-[1fr_360px]"><section className="panel rounded-3xl p-8 text-center">{state.round.type === "word" ? <div className="flex flex-wrap justify-center gap-4">{state.round.letters.map((letter, index) => <span className="flex h-24 w-20 items-center justify-center rounded-2xl bg-white text-5xl font-black text-slate-950" key={`${letter}-${index}`}>{letter}</span>)}<span className="flex h-24 w-20 items-center justify-center rounded-2xl border-4 border-dashed border-cyan-300 text-5xl">★</span></div> : <><div className="flex flex-wrap justify-center gap-4">{state.round.numbers.map((number, index) => <span className="flex h-24 w-20 items-center justify-center rounded-2xl bg-white text-4xl font-black text-slate-950" key={`${number}-${index}`}>{number}</span>)}</div><p className="mt-10 text-lg text-slate-300">Hedef sayı</p><strong className="text-7xl text-cyan-300">{state.round.target}</strong>{state.round.description && <p className="mt-4 text-slate-300">{state.round.description}</p>}</>}<div className="mt-10 flex flex-wrap justify-center gap-3"><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => command("pause")}>{state.paused ? "Devam et" : "Süreyi durdur"}</button><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => command("add-time", { seconds: 15 })}>+15 sn</button><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => command("finish")}>Turu bitir</button></div></section><div className="space-y-8"><Approvals command={command} lobby={false} state={state} /><Scoreboard command={command} teams={state.teams} /></div></div>{notice}</main>;
  if (state.phase === "round-results") return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-8 flex justify-between"><div><p className="text-cyan-300">{state.matchRound}. tur sonucu</p><h1 className="text-4xl font-bold">Cevaplar</h1></div><button className="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-slate-950" onClick={() => command("start")}>Sonraki tur</button></header><div className="grid gap-8 xl:grid-cols-[1fr_360px]"><section className="panel rounded-3xl p-6">{state.themedWord && <p className="mb-5 rounded-xl bg-cyan-400/15 p-4 text-cyan-200">Gizli kelime: <strong>{state.themedWord}</strong></p>}{state.numberSolution && <p className="mb-5 rounded-xl bg-cyan-400/15 p-4 text-cyan-200">En iyi çözüm: <strong>{state.numberSolution}</strong></p>}{state.submissions.map((item) => <div className="border-b border-white/10 py-4" key={`${item.teamId}-${item.answer}`}><div className="flex items-center justify-between"><span>{item.teamName}</span><strong>{item.answer}{item.value !== undefined ? ` = ${item.value}` : ""}</strong><strong className="text-cyan-300">+{item.score}</strong><span>{item.status === "accepted" ? "TDK doğruladı" : "Reddedildi"}</span></div>{item.status === "accepted" && item.meanings?.length ? <ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-slate-300">{item.meanings.map((meaning, index) => <li key={`${item.teamId}-${item.answer}-${index}`}>{meaning}</li>)}</ol> : null}</div>)}</section><div className="space-y-8"><Approvals command={command} lobby={false} state={state} /><Scoreboard command={command} teams={state.teams} /></div></div>{notice}</main>;
  if (state.phase === "game-results") return <main className="app-shell flex min-h-screen items-center justify-center p-6"><section className="panel confetti w-full max-w-4xl rounded-3xl p-10 text-center"><p className="text-cyan-300">Oyun tamamlandı</p><h1 className="mt-3 text-5xl font-black">Kazanan: {state.winner?.name}</h1><div className="mt-10 grid grid-cols-3 gap-4">{state.teams.slice(0, 3).map((team, index) => <div className={`rounded-3xl p-6 ${index === 0 ? "bg-cyan-400 text-slate-950" : "bg-white/10"}`} key={team.id}><p>{index + 1}. takım</p><strong className="mt-3 block text-2xl">{team.name}</strong><strong className="mt-3 block text-4xl">{team.score}</strong></div>)}</div><div className="mt-8 flex justify-center gap-3"><a className="rounded-xl border border-white/30 px-5 py-3" href="/api/results.csv">CSV indir</a><a className="rounded-xl border border-white/30 px-5 py-3" href="/api/results.json">JSON indir</a><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => command("start")}>Yeni oyun</button></div></section>{notice}</main>;
  return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-10 flex justify-between"><div><p className="text-cyan-300">Kurumsal Ice Breaker</p><h1 className="text-4xl font-bold">Bir Kelime Bir İşlem</h1></div><div className="flex gap-3"><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => command("reset")}>Oyunu sıfırla</button><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => command("start")}>Oyunu başlat</button></div></header><div className="grid gap-8 lg:grid-cols-2"><section className="panel rounded-3xl p-8 text-center"><div className="inline-block rounded-2xl bg-white p-4"><QRCodeSVG includeMargin size={260} value={joinUrl} /></div><p className="mt-6 break-all text-cyan-200">{joinUrl}</p></section><div className="space-y-8"><Approvals command={command} lobby state={state} /><Scoreboard command={command} teams={state.teams} /></div></div>{notice}</main>;
}
