import { FormEvent, useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { socket } from "../socket";
import type { GameState, Submission, Team } from "../types";

const emptyState: GameState = { phase: "lobby", teams: [], round: null, submissions: [], matchRound: 0, totalRounds: 0, roundType: null, teamMode: "team", winner: null, numberSolution: null, themedWord: null, paused: false };

function useRemainingSeconds(endsAt?: number) {
  const [remaining, setRemaining] = useState(0);
  useEffect(() => {
    if (!endsAt) return;
    const timer = window.setInterval(() => setRemaining(Math.max(0, Math.ceil((endsAt - Date.now()) / 1000))), 250);
    return () => window.clearInterval(timer);
  }, [endsAt]);
  return remaining;
}

function Scoreboard({ teams }: { teams: Team[] }) {
  return <aside className="panel rounded-3xl p-6"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">Canlı skor</p><ol className="mt-5 space-y-3">{teams.map((team, index) => <li className="flex items-center justify-between rounded-2xl bg-white/5 px-4 py-3" key={team.id}><span>{index + 1}. {team.name}</span><strong className="text-2xl text-cyan-300">{team.score}</strong></li>)}</ol></aside>;
}

export function HostPage() {
  const [pin, setPin] = useState("");
  const [authenticated, setAuthenticated] = useState(false);
  const [error, setError] = useState("");
  const [state, setState] = useState<GameState>(emptyState);
  const [joinUrl, setJoinUrl] = useState(`${window.location.protocol}//${window.location.host}/join`);
  const remaining = useRemainingSeconds(state.round?.endsAt);
  useEffect(() => {
    const update = (next: GameState) => setState(next);
    const request = () => socket.emit("game:state:request");
    socket.on("game:state", update); socket.on("connect", request); request();
    fetch(`/api/join-url?port=${window.location.port || "80"}`).then((response) => response.json()).then(({ url }) => setJoinUrl(url)).catch(() => undefined);
    return () => { socket.off("game:state", update); socket.off("connect", request); };
  }, []);
  function authenticate(event: FormEvent) { event.preventDefault(); socket.emit("host:authenticate", pin, (result: { ok: boolean }) => { setAuthenticated(result.ok); setError(result.ok ? "" : "PIN doğrulanamadı."); }); }
  if (!authenticated) return <main className="app-shell flex min-h-screen items-center justify-center p-6"><form className="panel w-full max-w-md rounded-3xl p-10" onSubmit={authenticate}><h1 className="text-4xl font-bold">Bir Kelime Bir İşlem</h1><label className="mt-8 block">Host PIN</label><input autoFocus className="mt-2 w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3" onChange={(event) => setPin(event.target.value)} type="password" value={pin} />{error && <p className="mt-3 text-red-300">{error}</p>}<button className="mt-6 w-full rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Devam et</button></form></main>;
  const isActive = state.phase === "word" || state.phase === "number";
  if (isActive && state.round) return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-8 flex justify-between"><div><p className="text-cyan-300">{state.matchRound}. tur / {state.totalRounds} · {state.round.type === "word" ? "Kelime" : "İşlem"}</p><h1 className="text-4xl font-bold">{state.round.type === "word" ? "Bir Kelime" : "Bir İşlem"}</h1></div><strong className="text-6xl text-cyan-300">{remaining}s</strong></header><div className="h-4 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-cyan-400" style={{ width: `${(remaining / state.round.durationSeconds) * 100}%` }} /></div><div className="mt-8 grid gap-8 xl:grid-cols-[1fr_360px]"><section className="panel rounded-3xl p-8 text-center">{state.round.type === "word" ? <div className="flex flex-wrap justify-center gap-4">{state.round.letters.map((letter, index) => <span className="flex h-24 w-20 items-center justify-center rounded-2xl bg-white text-5xl font-black text-slate-950" key={`${letter}-${index}`}>{letter}</span>)}<span className="flex h-24 w-20 items-center justify-center rounded-2xl border-4 border-dashed border-cyan-300 text-5xl">★</span></div> : <><div className="flex flex-wrap justify-center gap-4">{state.round.numbers.map((number, index) => <span className="flex h-24 w-20 items-center justify-center rounded-2xl bg-white text-4xl font-black text-slate-950" key={`${number}-${index}`}>{number}</span>)}</div><p className="mt-10 text-lg text-slate-300">Hedef sayı</p><strong className="text-7xl text-cyan-300">{state.round.target}</strong>{state.round.description && <p className="mt-4 text-slate-300">{state.round.description}</p>}</>}<div className="mt-10 flex flex-wrap justify-center gap-3"><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => socket.emit("host:round:pause")}>{state.paused ? "Devam et" : "Süreyi durdur"}</button><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => socket.emit("host:round:add-time", 15)}>+15 sn</button><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => socket.emit("host:round:finish")}>Turu bitir</button></div></section><Scoreboard teams={state.teams} /></div></main>;
  if (state.phase === "round-results") return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-8 flex justify-between"><div><p className="text-cyan-300">{state.matchRound}. tur sonucu</p><h1 className="text-4xl font-bold">Cevaplar</h1></div><button className="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-slate-950" onClick={() => socket.emit("host:round:start")}>Sonraki tur</button></header><div className="grid gap-8 xl:grid-cols-[1fr_360px]"><section className="panel rounded-3xl p-6">{state.themedWord && <p className="mb-5 rounded-xl bg-cyan-400/15 p-4 text-cyan-200">Gizli kelime: <strong>{state.themedWord}</strong></p>}{state.numberSolution && <p className="mb-5 rounded-xl bg-cyan-400/15 p-4 text-cyan-200">En iyi çözüm: <strong>{state.numberSolution}</strong></p>}{state.submissions.map((item) => <div className="border-b border-white/10 py-4" key={item.teamId}><div className="flex items-center justify-between"><span>{item.teamName}</span><strong>{item.answer}{item.value !== undefined ? ` = ${item.value}` : ""}</strong><strong className="text-cyan-300">+{item.score}</strong><span>{item.status === "accepted" ? "TDK doğruladı" : "Reddedildi"}</span></div>{item.status === "accepted" && item.meanings?.length ? <ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-slate-300">{item.meanings.map((meaning, index) => <li key={`${item.teamId}-${index}`}>{meaning}</li>)}</ol> : null}</div>)}</section><Scoreboard teams={state.teams} /></div></main>;
  if (state.phase === "game-results") return <main className="app-shell flex min-h-screen items-center justify-center p-6"><section className="panel confetti w-full max-w-4xl rounded-3xl p-10 text-center"><p className="text-cyan-300">Oyun tamamlandı</p><h1 className="mt-3 text-5xl font-black">Kazanan: {state.winner?.name}</h1><div className="mt-10 grid grid-cols-3 gap-4">{state.teams.slice(0, 3).map((team, index) => <div className={`rounded-3xl p-6 ${index === 0 ? "bg-cyan-400 text-slate-950" : "bg-white/10"}`} key={team.id}><p>{index + 1}. takım</p><strong className="mt-3 block text-2xl">{team.name}</strong><strong className="mt-3 block text-4xl">{team.score}</strong></div>)}</div><div className="mt-8 flex justify-center gap-3"><a className="rounded-xl border border-white/30 px-5 py-3" href="/api/results.csv">CSV indir</a><a className="rounded-xl border border-white/30 px-5 py-3" href="/api/results.json">JSON indir</a><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => socket.emit("host:round:start")}>Yeni oyun</button></div></section></main>;
  return <main className="app-shell min-h-screen p-6 lg:p-10"><header className="mb-10 flex justify-between"><div><p className="text-cyan-300">Kurumsal Ice Breaker</p><h1 className="text-4xl font-bold">Bir Kelime Bir İşlem</h1></div><div className="flex gap-3"><button className="rounded-xl border border-white/30 px-5 py-3" onClick={() => socket.emit("host:teams:reset")}>Oyunu sıfırla</button><button className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950" onClick={() => socket.emit("host:round:start")}>Oyunu başlat</button></div></header><div className="grid gap-8 lg:grid-cols-2"><section className="panel rounded-3xl p-8 text-center"><div className="inline-block rounded-2xl bg-white p-4"><QRCodeSVG includeMargin size={260} value={joinUrl} /></div><p className="mt-6 break-all text-cyan-200">{joinUrl}</p></section><Scoreboard teams={state.teams} /></div></main>;
}
