import { FormEvent, useEffect, useMemo, useState } from "react";
import { post, useGame } from "../game";
import type { NumberRound, WordRound } from "../types";

const tokenKey = "bkb-team-token";
const teamIdKey = "bkb-team-id";
const nameKey = "bkb-team-name";
function storedValue(key: string) { try { return localStorage.getItem(key); } catch { return null; } }
function storeValue(key: string, value: string) { try { localStorage.setItem(key, value); } catch { /* storage blocked: the team rejoins as a new team after a reload */ } }
function removeValue(key: string) { try { localStorage.removeItem(key); } catch { /* storage blocked: nothing was saved */ } }
type JoinResult = { gameId: string; teamId: string; token: string; name: string; teamStatus: "pending" | "approved" };
// One join at a time: page load and a game reset can both trigger one, and parallel joins without a valid token would create duplicate teams.
let joining: Promise<void> | null = null;
function normalize(value: string) { return value.toLocaleUpperCase("tr-TR"); }
function matchingLetterIndex(available: string[], letter: string) { const variants = letter === "I" || letter === "İ" ? ["I", "İ"] : letter === "O" || letter === "Ö" ? ["O", "Ö"] : letter === "U" || letter === "Ü" ? ["U", "Ü"] : letter === "G" || letter === "Ğ" ? ["G", "Ğ"] : letter === "C" || letter === "Ç" ? ["C", "Ç"] : [letter]; return available.findIndex((candidate) => variants.includes(candidate)); }
type Tile = { letter: string; joker: boolean };
const turkishLetters = ["A", "B", "C", "Ç", "D", "E", "F", "G", "Ğ", "H", "I", "İ", "J", "K", "L", "M", "N", "O", "Ö", "P", "R", "S", "Ş", "T", "U", "Ü", "V", "Y", "Z"];
// Mirrors canBuildWord in server/wordGame.ts: only a tile explicitly marked as joker may be a letter outside the round.
function canBuild(tiles: Tile[], round: WordRound) { const available = [...round.letters]; let jokers = 0; for (const tile of tiles) { if (tile.joker) { jokers += 1; continue; } const index = matchingLetterIndex(available, tile.letter); if (index < 0) return false; available.splice(index, 1); } return jokers <= 1 && tiles.length <= round.letters.length + 1; }
function toTiles(letters: string[]): Tile[] { return letters.map((letter) => ({ letter, joker: false })); }
function tilesText(tiles: Tile[]) { return tiles.map((tile) => tile.letter).join(""); }
function jokerPosition(tiles: Tile[]) { const index = tiles.findIndex((tile) => tile.joker); return index >= 0 ? index : null; }

export function JoinPage() {
  const { state, online } = useGame(); const [name, setName] = useState(storedValue(nameKey) ?? ""); const [joinedGameId, setJoinedGameId] = useState<string | null>(null); const [answer, setAnswer] = useState(""); const [tiles, setTiles] = useState<Tile[]>([]); const [pickingJoker, setPickingJoker] = useState(false); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [joinStatus, setJoinStatus] = useState<JoinResult["teamStatus"] | null>(null);
  const joined = joinedGameId !== null;
  // Approved teams are the ones in state.teams; the others' status is in state.statuses. Until the state catches up with the join, the join response decides.
  const teamId = storedValue(teamIdKey) ?? ""; const myStatus = !joined ? null : state.teams.some((team) => team.id === teamId) ? "approved" : state.statuses[teamId] ?? joinStatus; const status = online === null ? "Bağlanıyor…" : online ? "Bağlantı kuruldu" : "Bağlantı yeniden kuruluyor…";
  const mine = useMemo(() => state.submissions.filter((item) => item.teamId === storedValue(teamIdKey)), [state.submissions]);
  function join(teamName: string) { const cleaned = teamName.trim(); if (!cleaned) return setError("Geçerli bir takım adı girin."); if (joining) return; joining = post<JoinResult>("/api/join", { name: cleaned, token: storedValue(tokenKey) }).then((result) => { if (!result.ok) { if (result.status === 200) removeValue(nameKey); return setError(result.message ?? "Katılım yapılamadı."); } storeValue(tokenKey, result.token); storeValue(teamIdKey, result.teamId); storeValue(nameKey, result.name); setName(result.name); setJoinStatus(result.teamStatus); setJoinedGameId(result.gameId); setError(""); }).finally(() => { joining = null; }); }
  // Rejoin with the saved team on page load, and again after the host resets the game (new gameId).
  useEffect(() => { const saved = storedValue(nameKey); if (saved && storedValue(tokenKey) && state.gameId && state.gameId !== joinedGameId) join(saved); }, [state.gameId, joinedGameId]);
  useEffect(() => { setSubmitted(false); setAnswer(""); setTiles([]); setPickingJoker(false); }, [state.round?.id]);
  // Rejected or removed: back to the form. The saved name is dropped so a reload doesn't reapply under it; a different name may apply again.
  useEffect(() => { if (myStatus !== "rejected" && myStatus !== "removed") return; setJoinedGameId(null); setJoinStatus(null); removeValue(nameKey); setName(""); setError(myStatus === "rejected" ? "Katılımınız host tarafından reddedildi. Farklı bir adla tekrar deneyebilirsiniz." : "Host sizi oyundan çıkardı. Farklı bir adla tekrar katılabilirsiniz."); }, [myStatus]);
  function submit(event?: FormEvent) { event?.preventDefault(); const payload = state.phase === "word" ? { answer: tilesText(tiles), jokerIndex: jokerPosition(tiles) } : { answer }; post("/api/submit", { ...payload, token: storedValue(tokenKey) }).then((result) => { if (result.ok) { setSubmitted(false); setAnswer(""); setTiles([]); setPickingJoker(false); setError(""); } else setError(result.message ?? "Cevap gönderilemedi."); }); }
  function add(value: string) { if (!state.round || submitted) return; if (state.round.type === "word") { const next = [...tiles, { letter: value, joker: false }]; if (canBuild(next, state.round)) setTiles(next); } else setAnswer((current) => `${current}${value}`); }
  function addJoker(letter: string, round: WordRound) { const next = [...tiles, { letter, joker: true }]; if (canBuild(next, round)) setTiles(next); setPickingJoker(false); }
  // Typing appends or trims tiles so an existing joker survives; any other edit is re-read as plain round letters.
  function typeWord(value: string, round: WordRound) { const next = Array.from(normalize(value).replace(/[^A-ZÇĞİÖŞÜ]/gu, "")); const current = tiles.map((tile) => tile.letter); let candidate: Tile[]; if (next.length >= current.length && current.every((letter, index) => next[index] === letter)) candidate = [...tiles, ...toTiles(next.slice(current.length))]; else if (next.length < current.length && next.every((letter, index) => current[index] === letter)) candidate = tiles.slice(0, next.length); else candidate = toTiles(next); if (canBuild(candidate, round)) setTiles(candidate); }
  if (!joined) return <main className="app-shell flex min-h-screen items-center justify-center p-5"><form className="panel w-full max-w-md rounded-3xl p-7" onSubmit={(event) => { event.preventDefault(); join(name); }}><p className="text-cyan-300">Lobiye katıl</p><h1 className="mt-2 text-3xl font-bold">Takımınızın adı</h1><input autoFocus className="mt-8 w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3" maxLength={32} onChange={(event) => setName(event.target.value)} value={name} />{error && <p className="mt-3 text-red-300">{error}</p>}<button className="mt-6 w-full rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">Oyuna katıl</button><p className="mt-6 text-center text-xs text-slate-400">{status}</p></form></main>;
  if (myStatus === "pending") return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7 text-center"><p className="text-cyan-300">Takımınız: <strong>{name}</strong></p><h1 className="mt-3 text-3xl font-bold">Host onayı bekleniyor</h1><p className="mt-4 text-slate-300">Host katılımınızı onayladığında oyun burada açılacak.</p><p className="mt-6 text-xs text-slate-400">{status}</p></section></main>;
  if (state.phase === "word" && state.round?.type === "word") return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7"><p className="text-cyan-300">{state.matchRound}. tur / {state.totalRounds} · Kelime</p><h1 className="mt-2 text-2xl font-bold">En uzun kelimeyi oluşturun</h1>{submitted ? <div className="py-10 text-center"><h2 className="text-3xl font-bold text-emerald-300">Cevabınız alındı</h2><button className="mt-6 text-cyan-300 underline" onClick={() => setSubmitted(false)}>Cevabı düzenle</button></div> : <form onSubmit={submit}><input className="mt-7 w-full rounded-xl border border-cyan-300 bg-white/10 px-4 py-4 text-center text-3xl font-bold" onChange={(event) => typeWord(event.target.value, state.round as WordRound)} value={tilesText(tiles)} />{jokerPosition(tiles) !== null && <p className="mt-2 text-center text-sm text-cyan-200">★ Joker: <strong>{tiles[jokerPosition(tiles)!].letter}</strong> ({jokerPosition(tiles)! + 1}. harf)</p>}{pickingJoker ? <div className="mt-6 rounded-2xl border border-dashed border-cyan-300 p-4"><p className="text-sm text-slate-300">Jokerin yerine geçeceği harfi seçin</p><div className="mt-3 grid grid-cols-6 gap-2">{turkishLetters.map((letter) => <button className="rounded-lg bg-cyan-400/20 py-2 text-lg font-bold" key={letter} onClick={() => addJoker(letter, state.round as WordRound)} type="button">{letter}</button>)}</div><button className="mt-3 text-sm text-cyan-300 underline" onClick={() => setPickingJoker(false)} type="button">Vazgeç</button></div> : <div className="mt-6 grid grid-cols-3 gap-3">{state.round.letters.map((letter, index) => <button className="rounded-xl bg-white py-4 text-2xl font-black text-slate-950" key={`${letter}-${index}`} onClick={() => add(letter)} type="button">{letter}</button>)}<button className="rounded-xl border-2 border-dashed border-cyan-300 text-2xl disabled:opacity-30" disabled={jokerPosition(tiles) !== null || tiles.length > state.round.letters.length} onClick={() => setPickingJoker(true)} type="button">★</button></div>}<div className="mt-4 flex gap-3"><button className="flex-1 rounded-xl border border-white/30 py-3" onClick={() => setTiles((current) => current.slice(0, -1))} type="button">Sil</button><button className="flex-[2] rounded-xl bg-cyan-400 py-3 font-bold text-slate-950" disabled={!tiles.length}>Gönder</button></div></form>}{error && <p className="mt-3 text-red-300">{error}</p>}</section></main>;
  if (state.phase === "number" && state.round?.type === "number") { const round = state.round as NumberRound; return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7"><p className="text-cyan-300">{state.matchRound}. tur / {state.totalRounds} · İşlem</p><h1 className="mt-2 text-2xl font-bold">Hedef: <strong className="text-cyan-300">{round.target}</strong></h1>{round.description && <p className="mt-2 text-slate-300">{round.description}</p>}{submitted ? <div className="py-10 text-center"><h2 className="text-3xl font-bold text-emerald-300">Cevabınız alındı</h2><button className="mt-6 text-cyan-300 underline" onClick={() => setSubmitted(false)}>Cevabı düzenle</button></div> : <form onSubmit={submit}><input className="mt-7 w-full rounded-xl border border-cyan-300 bg-white/10 px-4 py-4 text-center text-2xl font-bold" onChange={(event) => setAnswer(event.target.value)} value={answer} /><div className="mt-6 grid grid-cols-3 gap-3">{round.numbers.map((number, index) => <button className="rounded-xl bg-white py-4 text-2xl font-black text-slate-950" key={`${number}-${index}`} onClick={() => add(String(number))} type="button">{number}</button>)}{["+", "-", "×", "÷", "(", ")"].map((operator) => <button className="rounded-xl border border-cyan-300 py-4 text-2xl" key={operator} onClick={() => add(operator)} type="button">{operator}</button>)}</div><div className="mt-4 flex gap-3"><button className="flex-1 rounded-xl border border-white/30 py-3" onClick={() => setAnswer((current) => current.slice(0, -1))} type="button">Sil</button><button className="flex-[2] rounded-xl bg-cyan-400 py-3 font-bold text-slate-950" disabled={!answer}>Gönder</button></div></form>}{error && <p className="mt-3 text-red-300">{error}</p>}</section></main>; }
  if (state.phase === "round-results") return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7 text-center"><h1 className="text-3xl font-bold">Tur tamamlandı</h1>{mine.length ? <ol className="mt-4 space-y-2 text-left">{mine.map((item, index) => <li className="flex justify-between" key={`${item.answer}-${index}`}><span>Cevabınız: <strong className="text-cyan-300">{item.answer}</strong></span><strong>+{item.score} puan</strong></li>)}</ol> : null}<ol className="mt-7 space-y-2 text-left">{state.teams.map((team, index) => <li className="flex justify-between" key={team.id}><span>{index + 1}. {team.name}</span><strong className="text-cyan-300">{team.score}</strong></li>)}</ol></section></main>;
  if (state.phase === "game-results") return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7 text-center"><p className="text-cyan-300">Oyun tamamlandı</p><h1 className="mt-3 text-4xl font-black">Kazanan: {state.winner?.name}</h1><ol className="mt-8 space-y-3 text-left">{state.teams.map((team, index) => <li className="flex justify-between" key={team.id}><span>{index + 1}. {team.name}</span><strong className="text-cyan-300">{team.score}</strong></li>)}</ol></section></main>;
  return <main className="app-shell flex min-h-screen items-center justify-center p-5"><section className="panel w-full max-w-md rounded-3xl p-7 text-center"><h1 className="text-3xl font-bold">Katılımınız alındı</h1><p className="mt-4 text-slate-300">Host oyunu başlattığında tur burada açılacak.</p><p className="mt-6 text-xs text-slate-400">{status}</p></section></main>;
}
