import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { EventLogo, Logo, PoweredBy } from "../Brand";
import { evaluateNumberExpression } from "../../server/numberExpression";
import { post, useGame } from "../game";
import { useFinalReveal } from "../reveal";
import type { NumberRound, WordRound } from "../types";

const tokenKey = "bkb-team-token";
const teamIdKey = "bkb-team-id";
const nameKey = "bkb-team-name";
function storedValue(key: string) { try { return localStorage.getItem(key); } catch { return null; } }
function storeValue(key: string, value: string) { try { localStorage.setItem(key, value); } catch { /* storage blocked: the team rejoins as a new team after a reload */ } }
function removeValue(key: string) { try { localStorage.removeItem(key); } catch { /* storage blocked: nothing was saved */ } }
type JoinResult = { gameId: string; teamId: string; token: string; name: string; teamStatus: "pending" | "approved"; expired?: boolean };
// One join at a time: page load and a game reset can both trigger one, and parallel joins without a valid token would create duplicate teams.
let joining: Promise<void> | null = null;
function normalize(value: string) { return value.toLocaleUpperCase("tr-TR"); }
function matchingLetterIndex(available: string[], letter: string) { const variants = letter === "I" || letter === "İ" ? ["I", "İ"] : letter === "O" || letter === "Ö" ? ["O", "Ö"] : letter === "U" || letter === "Ü" ? ["U", "Ü"] : letter === "G" || letter === "Ğ" ? ["G", "Ğ"] : letter === "C" || letter === "Ç" ? ["C", "Ç"] : [letter]; return available.findIndex((candidate) => variants.includes(candidate)); }
type Tile = { letter: string; joker: boolean };
const turkishLetters = ["A", "B", "C", "Ç", "D", "E", "F", "G", "Ğ", "H", "I", "İ", "J", "K", "L", "M", "N", "O", "Ö", "P", "R", "S", "Ş", "T", "U", "Ü", "V", "Y", "Z"];
// Mirrors canBuildWord in server/wordGame.ts: only a tile explicitly marked as joker may be a letter outside the round.
function canBuild(tiles: Tile[], round: WordRound) { const available = [...round.letters]; let jokers = 0; for (const tile of tiles) { if (tile.joker) { jokers += 1; continue; } const index = matchingLetterIndex(available, tile.letter); if (index < 0) return false; available.splice(index, 1); } return jokers <= 1 && tiles.length <= round.letters.length + 1; }
function toTiles(letters: string[]): Tile[] { return letters.map((letter) => ({ letter, joker: false })); }
function tilesText(tiles: Tile[]) { return tiles.map((tile) => tile.letter).join(""); }
// Live intermediate result in a number round, using the server's own parser. Errors from a half-typed expression are not shown, only rule breaks.
const ruleBreaks = ["Her sayı en fazla bir kez kullanılabilir.", "Bölme tam sayı olmalı.", "Ara sonuçlar pozitif tam sayı olmalı."];
function liveResult(expression: string, round: NumberRound) {
  const result = evaluateNumberExpression(expression, round.numbers);
  if ("value" in result && result.value !== undefined) { const distance = Math.abs(result.value - round.target); return { tone: distance === 0 ? "text-brand-yellow" : "text-turquoise", text: distance === 0 ? `= ${result.value} · tam isabet!` : `= ${result.value} · hedefe ${distance} uzak` }; }
  return "message" in result && result.message && ruleBreaks.includes(result.message) ? { tone: "text-brand-orange", text: result.message } : null;
}
function jokerPosition(tiles: Tile[]) { const index = tiles.findIndex((tile) => tile.joker); return index >= 0 ? index : null; }

export function JoinPage() {
  const { state, online } = useGame(); const [name, setName] = useState(storedValue(nameKey) ?? ""); const [joinedGameId, setJoinedGameId] = useState<string | null>(null); const [answer, setAnswer] = useState(""); const [tiles, setTiles] = useState<Tile[]>([]); const [pickingJoker, setPickingJoker] = useState(false); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [info, setInfo] = useState(""); const [joinStatus, setJoinStatus] = useState<JoinResult["teamStatus"] | null>(null);
  // Same last-to-first reveal as the projector, started when the final results arrive.
  const final = useFinalReveal(state.teams.length, state.phase === "game-results");
  const joined = joinedGameId !== null;
  // Approved teams are the ones in state.teams; the others' status is in state.statuses. Until the state catches up with the join, the join response decides.
  const teamId = storedValue(teamIdKey) ?? ""; const myStatus = !joined ? null : state.teams.some((team) => team.id === teamId) ? "approved" : state.statuses[teamId] ?? joinStatus; const status = online === null ? "Bağlanıyor…" : online ? "Bağlantı kuruldu" : "Bağlantı yeniden kuruluyor…";
  const mine = useMemo(() => state.submissions.filter((item) => item.teamId === storedValue(teamIdKey)), [state.submissions]);
  // rejoin: an automatic attempt that may only resume this game's team. If the game was reset, the form comes back with the old name filled in and nothing is sent until the player confirms.
  function join(teamName: string, rejoin = false) { const cleaned = teamName.trim(); if (!cleaned) return setError("Geçerli bir takım adı girin."); if (joining) return; joining = post<JoinResult>("/api/join", { name: cleaned, token: storedValue(tokenKey), rejoin }).then((result) => { if (!result.ok && result.expired) { setJoinedGameId(null); setJoinStatus(null); setName(cleaned); setError(""); setInfo("Yeni bir oyun başladı. Takım adınızı kontrol edip yeniden katılın."); return; } if (!result.ok) { if (result.status === 200) removeValue(nameKey); return setError(result.message ?? "Katılım yapılamadı."); } setInfo(""); storeValue(tokenKey, result.token); storeValue(teamIdKey, result.teamId); storeValue(nameKey, result.name); setName(result.name); setJoinStatus(result.teamStatus); setJoinedGameId(result.gameId); setError(""); }).finally(() => { joining = null; }); }
  // Resume the saved team on page load or reconnect, and check again when the game id changes; a reset game sends the player back to the form.
  useEffect(() => { const saved = storedValue(nameKey); if (saved && storedValue(tokenKey) && state.gameId && state.gameId !== joinedGameId) join(saved, true); }, [state.gameId, joinedGameId]);
  useEffect(() => { setSubmitted(false); setAnswer(""); setTiles([]); setPickingJoker(false); }, [state.round?.id]);
  // Rejected or removed: back to the form. The saved name is dropped so a reload doesn't reapply under it; a different name may apply again.
  useEffect(() => { if (myStatus !== "rejected" && myStatus !== "removed") return; setJoinedGameId(null); setJoinStatus(null); removeValue(nameKey); setName(""); setError(myStatus === "rejected" ? "Katılımınız host tarafından reddedildi. Farklı bir adla tekrar deneyebilirsiniz." : "Host sizi oyundan çıkardı. Farklı bir adla tekrar katılabilirsiniz."); }, [myStatus]);
  function submit(event?: FormEvent) { event?.preventDefault(); const payload = state.phase === "word" ? { answer: tilesText(tiles), jokerIndex: jokerPosition(tiles) } : { answer }; post("/api/submit", { ...payload, token: storedValue(tokenKey) }).then((result) => { if (result.ok) { setSubmitted(false); setAnswer(""); setTiles([]); setPickingJoker(false); setError(""); } else setError(result.message ?? "Cevap gönderilemedi."); }); }
  function add(value: string) { if (!state.round || submitted) return; if (state.round.type === "word") { const next = [...tiles, { letter: value, joker: false }]; if (canBuild(next, state.round)) setTiles(next); } else setAnswer((current) => `${current}${value}`); }
  function addJoker(letter: string, round: WordRound) { const next = [...tiles, { letter, joker: true }]; if (canBuild(next, round)) setTiles(next); setPickingJoker(false); }
  // Typing appends or trims tiles so an existing joker survives; any other edit is re-read as plain round letters.
  function typeWord(value: string, round: WordRound) { const next = Array.from(normalize(value).replace(/[^A-ZÇĞİÖŞÜ]/gu, "")); const current = tiles.map((tile) => tile.letter); let candidate: Tile[]; if (next.length >= current.length && current.every((letter, index) => next[index] === letter)) candidate = [...tiles, ...toTiles(next.slice(current.length))]; else if (next.length < current.length && next.every((letter, index) => current[index] === letter)) candidate = tiles.slice(0, next.length); else candidate = toTiles(next); if (canBuild(candidate, round)) setTiles(candidate); }
  // Every phone screen: the logo above one card.
  const screen = (content: ReactNode) => <main className="app-shell flex min-h-screen flex-col items-center justify-center gap-5 p-5"><div className="flex flex-col items-center"><Logo className="w-44" /><EventLogo className="h-9 w-auto" /></div>{content}<PoweredBy className="mt-2 h-6 w-auto opacity-80" /></main>;
  const roundLabel = (kind: string) => <p className="eyebrow">{state.matchRound}. tur / {state.totalRounds} · {kind}</p>;
  const sent = <div className="py-10 text-center"><h2 className="font-serif text-3xl font-bold text-brand-green">Cevabınız alındı</h2><button className="btn btn-ghost mt-6" onClick={() => setSubmitted(false)}>Cevabı düzenle</button></div>;
  const errorLine = error && <p className="mt-3 text-center text-brand-orange">{error}</p>;
  if (!joined) return screen(<form className="panel w-full max-w-md rounded-3xl p-7" onSubmit={(event) => { event.preventDefault(); join(name); }}><p className="eyebrow">Lobiye katıl</p><h1 className="mt-2 font-serif text-3xl font-bold">Takımınızın adı</h1><input autoFocus className="field mt-8 text-lg" maxLength={32} onChange={(event) => setName(event.target.value)} placeholder="Örn. Veri Kaşifleri" value={name} />{info && <p className="mt-3 text-center text-turquoise">{info}</p>}{errorLine}<button className="btn btn-primary mt-6 w-full py-4 text-lg">Oyuna katıl</button><p className="mt-6 text-center text-xs text-white/50">{status}</p></form>);
  if (myStatus === "pending") return screen(<section className="panel w-full max-w-md rounded-3xl p-7 text-center"><p className="eyebrow">Takımınız</p><p className="mt-2 text-2xl font-semibold">{name}</p><span className="relative mx-auto mt-8 flex h-4 w-4"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-turquoise opacity-75" /><span className="relative inline-flex h-4 w-4 rounded-full bg-turquoise" /></span><h1 className="mt-6 font-serif text-3xl font-bold">Host onayı bekleniyor</h1><p className="mt-4 text-white/70">Host katılımınızı onayladığında oyun burada açılacak.</p><p className="mt-6 text-xs text-white/50">{status}</p></section>);
  if (state.phase === "word" && state.round?.type === "word") return screen(<section className="panel w-full max-w-md rounded-3xl p-6">{roundLabel("Kelime")}<h1 className="mt-2 font-serif text-2xl font-bold">En uzun kelimeyi oluşturun</h1>{submitted ? sent : <form onSubmit={submit}><input className="field mt-6 border-turquoise/60 text-center text-3xl font-bold tracking-[0.15em]" onChange={(event) => typeWord(event.target.value, state.round as WordRound)} value={tilesText(tiles)} />{jokerPosition(tiles) !== null && <p className="mt-2 text-center text-sm text-turquoise">★ Joker: <strong>{tiles[jokerPosition(tiles)!].letter}</strong> ({jokerPosition(tiles)! + 1}. harf)</p>}{pickingJoker ? <div className="mt-5 rounded-2xl border border-dashed border-turquoise p-4"><p className="text-sm text-white/75">Jokerin yerine geçeceği harfi seçin</p><div className="mt-3 grid grid-cols-6 gap-2">{turkishLetters.map((letter) => <button className="rounded-xl bg-future/40 py-2 text-lg font-bold hover:bg-future" key={letter} onClick={() => addJoker(letter, state.round as WordRound)} type="button">{letter}</button>)}</div><button className="btn btn-ghost btn-sm mt-4" onClick={() => setPickingJoker(false)} type="button">Vazgeç</button></div> : <div className="mt-5 grid grid-cols-3 gap-3">{state.round.letters.map((letter, index) => <button className="tile h-16 text-3xl" key={`${letter}-${index}`} onClick={() => add(letter)} type="button">{letter}</button>)}<button className="tile-joker h-16 text-3xl disabled:opacity-30" disabled={jokerPosition(tiles) !== null || tiles.length > state.round.letters.length} onClick={() => setPickingJoker(true)} type="button">★</button></div>}<div className="mt-5 flex gap-3"><button className="btn btn-ghost flex-1" onClick={() => setTiles((current) => current.slice(0, -1))} type="button">Sil</button><button className="btn btn-primary flex-[2] text-lg" disabled={!tiles.length}>Gönder</button></div></form>}{errorLine}</section>);
  if (state.phase === "number" && state.round?.type === "number") { const round = state.round as NumberRound; return screen(<section className="panel w-full max-w-md rounded-3xl p-6">{roundLabel("İşlem")}<div className="mt-2 flex items-baseline gap-3"><h1 className="font-serif text-2xl font-bold">Hedef</h1><strong className="font-serif text-5xl text-turquoise">{round.target}</strong></div>{round.description && <p className="mt-2 text-white/70">{round.description}</p>}{submitted ? sent : <form onSubmit={submit}><input className="field mt-6 border-turquoise/60 text-center text-2xl font-bold" onChange={(event) => setAnswer(event.target.value)} value={answer} />{(() => { const live = state.liveResult && answer ? liveResult(answer, round) : null; return <p className={`mt-2 min-h-7 text-center text-lg font-semibold ${live?.tone ?? ""}`}>{live?.text ?? ""}</p>; })()}<div className="mt-5 grid grid-cols-3 gap-3">{round.numbers.map((number, index) => <button className="tile h-16 text-3xl" key={`${number}-${index}`} onClick={() => add(String(number))} type="button">{number}</button>)}{["+", "-", "×", "÷", "(", ")"].map((operator) => <button className="h-14 rounded-2xl border border-turquoise/60 text-3xl text-turquoise" key={operator} onClick={() => add(operator)} type="button">{operator}</button>)}</div><div className="mt-5 flex gap-3"><button className="btn btn-ghost flex-1" onClick={() => setAnswer((current) => current.slice(0, -1))} type="button">Sil</button><button className="btn btn-primary flex-[2] text-lg" disabled={!answer}>Gönder</button></div></form>}{errorLine}</section>); }
  const ranking = (revealing: boolean) => state.scoresHidden ? <p className="mt-6 rounded-2xl bg-white/5 px-4 py-3 text-sm font-semibold text-brand-yellow">Skorlar finalde açıklanacak</p> : <ol className="mt-6 space-y-2 text-left">{state.teams.map((team, index) => { const shown = !revealing || final.isRevealed(index + 1); return <li className={`flex items-center gap-3 rounded-2xl px-4 py-2 ${shown && team.id === teamId ? "bg-future/40 ring-1 ring-turquoise" : "bg-white/5"} ${revealing && shown ? "tile-pop" : ""}`} key={team.id}><span className="w-6 text-white/55">{index + 1}.</span>{shown ? <><span className="min-w-0 flex-1 truncate font-semibold">{team.name}</span><strong className="tabular-nums text-turquoise">{team.score}</strong></> : <span className="flex-1 select-none tracking-widest text-white/25 blur-[3px]">●●●●●●</span>}</li>; })}</ol>;
  if (state.phase === "round-results") return screen(<section className="panel w-full max-w-md rounded-3xl p-7 text-center"><p className="eyebrow">{state.matchRound}. tur</p><h1 className="mt-2 font-serif text-3xl font-bold">Tur tamamlandı</h1>{mine.length ? <ol className="mt-6 space-y-2 text-left">{mine.map((item, index) => <li className="flex items-center justify-between rounded-2xl bg-brand-green/10 px-4 py-2" key={`${item.answer}-${index}`}><strong className="font-serif text-xl tracking-wide">{item.answer}</strong><strong className="text-brand-green">+{item.score} puan</strong></li>)}</ol> : <p className="mt-4 text-white/60">Bu turda puan alan cevabınız olmadı.</p>}{ranking(false)}</section>);
  if (state.phase === "game-results") return screen(<section className={`panel w-full max-w-md rounded-3xl p-7 text-center ${final.done ? "confetti" : ""}`}><p className="eyebrow">Oyun tamamlandı</p>{final.done ? <>{state.winner?.id === teamId && <p className="mt-3 font-serif text-2xl font-bold text-brand-yellow">Tebrikler, kazandınız!</p>}<h1 className="tile-pop mt-3 font-serif text-4xl font-bold">Kazanan: <span className="text-brand-yellow">{state.winner?.name ?? "—"}</span></h1></> : <h1 className="mt-3 font-serif text-3xl font-bold">Sonuçlar açıklanıyor…</h1>}{ranking(true)}</section>);
  return screen(<section className="panel w-full max-w-md rounded-3xl p-7 text-center"><p className="eyebrow">Katılımınız alındı</p><p className="mt-3 font-serif text-3xl font-bold">{name}</p><p className="mt-4 text-white/70">Host oyunu başlattığında tur burada açılacak.</p><p className="mt-6 text-xs text-white/50">{status}</p></section>);
}
